export const USER_FETCHING = 'USER_FETCHING';
export const USER_FETCHED = 'USER_FETCHED';
export const MORE_USER_FETCHED = 'MORE_USER_FETCHED';
export const REPO_FETCHING = 'REPO_FETCHING';
export const REPO_FETCHED = 'REPO_FETCHED';
export const MORE_REPO_FETCHED = 'MORE_REPO_FETCHED';